- src/Avalonia.FuncUI.sln
- src/templates/Avalonia.FuncUI.ElmishTemplate/content/.template.config/template.json
- src/templates/Avalonia.FuncUI.ElmishTemplate/content/AppView.fs
- src/templates/Avalonia.FuncUI.ElmishTemplate/content/Avalonia.FuncUI.ElmishTemplate.fsproj
- src/templates/Avalonia.FuncUI.ElmishTemplate/content/Counter.fs
- src/templates/Avalonia.FuncUI.ElmishTemplate/content/Lib.fs
- src/templates/Avalonia.FuncUI.ElmishTemplate/content/Main.fs
This PR contains the minimum structure for a dotnet template. I used the elmish project from the examples folder to setup this template. You still would have to install it locally at this point though. The next steps should be improving on this template and then publishing it via nuget so you can directly install it from the web.
Screenshot of me installing the template from the project folder:
Creating the project:
Running the counter example after successfully building it:
> Add dotnet template folder and template project for ElmishTemplate

- src/Avalonia.FuncUI.Elmish/Library.fs
CheckAccess works all the way around. Access check should be after receiving the message as we don't know from which source we got it.
> Fixed sync dispatch

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.DSL/Avalonia.FuncUI.DSL.fsproj
- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI.UnitTests/Avalonia.FuncUI.UnitTests.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Examples/Examples.ClockApp/Examples.ClockApp.fsproj
- src/Examples/Examples.CounterApp/Counter.fs
- src/Examples/Examples.CounterApp/Examples.CounterApp.fsproj
- src/Examples/Examples.GameOfLife/Examples.GameOfLife.fsproj
- src/Examples/Examples.MusicPlayer/Examples.MusicPlayer.fsproj
- src/Examples/Examples.Presso/Examples.Presso.fsproj
I've noticed that `MusicPlayer` has stale reference of Avalonia (`0.9.2` ) that leads to a crash on start so I decided to update version there and elsewhere as well.
> Update Avalonia to 0.9.9

- src/Avalonia.FuncUI.DSL/ContentControl.fs
I've added horizontalContentAlignment and verticalContentAlignment because they were missing
> Add missing properties for ContentControl

- .github/workflows/publish.yml
- .github/workflows/pull-requests.yml
This PR closes #178 by creating a new workflow called `Build, Test and Publish release` which builds the library, runs all the UTs and publishes a new version to NuGet if the version has changed. Also took the opportunity to rename the old flow to `pull-request.yml` and `Build and test` and make it run only on new PRs to master. 
Heavily inspired by [FSharp.Data's flow](https://github.com/fsprojects/FSharp.Data/blob/main/.github/workflows/push-master.yml) and using the secret name that @dsyme provided in [here](https://github.com/fsprojects/Avalonia.FuncUI/issues/172#issuecomment-988945425). Validated with [Act](https://github.com/nektos/act).
> Automate package publication via GitHub Action

- src/Avalonia.FuncUI.Templates/Avalonia.FuncUI.Templates.fsproj
- src/Avalonia.FuncUI.Templates/content/BasicMvuTemplate/.template.config/template.json
- src/Avalonia.FuncUI.Templates/content/BasicMvuTemplate/BasicMvuTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/BasicMvuTemplate/Counter.fs
- src/Avalonia.FuncUI.Templates/content/BasicMvuTemplate/Program.fs
- src/Avalonia.FuncUI.Templates/content/BasicMvuTemplate/README.md
- src/Avalonia.FuncUI.Templates/content/BasicTemplate/.template.config/template.json
- src/Avalonia.FuncUI.Templates/content/BasicTemplate/BasicTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/BasicTemplate/Counter.fs
- src/Avalonia.FuncUI.Templates/content/BasicTemplate/Program.fs
- src/Avalonia.FuncUI.Templates/content/BasicTemplate/README.md
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/.template.config/template.json
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/About.fs
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/Counter.fs
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/FullMvuTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/Program.fs
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/README.md
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/Shell.fs
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/Styles.xaml
- src/Avalonia.FuncUI.Templates/content/FullTemplate/.template.config/template.json
- src/Avalonia.FuncUI.Templates/content/FullTemplate/About.fs
- src/Avalonia.FuncUI.Templates/content/FullTemplate/Counter.fs
- src/Avalonia.FuncUI.Templates/content/FullTemplate/FullTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/FullTemplate/Program.fs
- src/Avalonia.FuncUI.Templates/content/FullTemplate/README.md
- src/Avalonia.FuncUI.Templates/content/FullTemplate/Shell.fs
- src/Avalonia.FuncUI.Templates/content/FullTemplate/Styles.xaml
- src/Avalonia.FuncUI.sln
Hello everyone, I'm in order to ease releases and reduce the scattered maintenance, I tried to bring the  FuncUI templates into this repo.
This repo includes the following templates
- Counter MVU - `dotnet new funcui.basic.mvu`
- Counter Component - `dotnet new funcui.basic`
- Full Template MVU - `dotnet new funcui.full`
There are a few things I want to add and others to duscuss
- Full Template Component Version
- Removing Quickstart Template
- Make Component Templates the Default
- Adding a "Tutorial" Template 
For simple purposes I just want to add the Full Template with component version and switch it from draft to free to review that might be tomorrow, for the discuss ones, if you want to discuss in this PR or open an issue about them it would be nice as well
> add funcui templates

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.UnitTests/Avalonia.FuncUI.UnitTests.fsproj
- src/Examples/Elmish Examples/Examples.Elmish.ClockApp/Examples.Elmish.ClockApp.fsproj
- src/Examples/Elmish Examples/Examples.Elmish.CounterApp/Examples.Elmish.CounterApp.fsproj
- src/Examples/Elmish Examples/Examples.Elmish.GameOfLife/Examples.Elmish.GameOfLife.fsproj
- src/Examples/Elmish Examples/Examples.Elmish.MusicPlayer/Examples.Elmish.MusicPlayer.fsproj
- src/Examples/Elmish Examples/Examples.Elmish.Presso/Examples.Elmish.Presso.fsproj
This fixes the following issue:
https://github.com/fsprojects/Avalonia.FuncUI/issues/203
Problem is that some projects explicitly reference FSharp.Core 4.7.2 whereas most projects do not add explicit package reference.  The projects that don't add package reference implicitly add latest version of FSharp.Core which causes the examples to crash with a runtime linker error do to mismatch of FSharp.Core versions.
The approach taking in this PR is simply to remove explicit references to 4.7.2 as to keep all projects consistent.
> Remove package references to FSharp.Core 4.7.2

- src/Avalonia.FuncUI.DSL/Avalonia.FuncUI.DSL.fsproj
- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI.Templates/content/BasicMvuTemplate/BasicMvuTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/BasicTemplate/BasicTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/FullMvuTemplate/FullMvuTemplate.fsproj
- src/Avalonia.FuncUI.Templates/content/FullTemplate/FullTemplate.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
As released just yesterday, to keep up with upstream:
https://github.com/AvaloniaUI/Avalonia/releases/tag/0.10.15
This also bumps the version of FuncUI to 0.5.3 across all packages to publish the new version.
> Upgrade to Avalonia 0.10.15

- src/Avalonia.FuncUI.DSL/TreeView.fs
Hi,
I was having a go at a UI using a TreeView and I needed to handle a selection changed event, and I didn't see it in the current version.
I added a local extension method and that seemed to work ok, but I thought i'd see if it could be added to the build in bindings (I'm not sure what the situation is with just adding extra bindings to existing controls?)
Thanks
> Add onSelectedItemChanged to TreeView

- src/Avalonia.FuncUI.UnitTests/VirtualDom/VirtualDom.PatcherTests.fs
- src/Avalonia.FuncUI.sln
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Avalonia.FuncUI/Builder.fs
- src/Avalonia.FuncUI/DSL/Documents/Bold.fs
- src/Avalonia.FuncUI/DSL/Documents/Italic.fs
- src/Avalonia.FuncUI/DSL/Documents/LineBreak.fs
- src/Avalonia.FuncUI/DSL/Documents/Run.fs
- src/Avalonia.FuncUI/DSL/Documents/Span.fs
- src/Avalonia.FuncUI/DSL/Documents/Underline.fs
- src/Avalonia.FuncUI/DSL/Primitives/TextElement.fs
- src/Avalonia.FuncUI/DSL/RichTextBlock.fs
- src/Avalonia.FuncUI/Library.fs
- src/Avalonia.FuncUI/Types.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Delta.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Differ.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Misc.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Patcher.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.fs
- src/Examples/Component Examples/Examples.InlineText/Examples.InlineText.fsproj
- src/Examples/Component Examples/Examples.InlineText/Program.fs
- src/Examples/Component Examples/Examples.InlineText/View.fs
This PR attempts to add support for the new RichTextBlock introduced in Avalonia v11. Although adding the new control is pretty straightforward, the main challenge comes from the new inline elements that were introduced for the new control, since these should be used the same way as controls are used but are not controls per se.
The new control contains a property with a collection of [Inlines](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Documents/Inline.cs), which are themselves subclasses of StyledElements. Each inline then defines how that portion of the text should be styled, with `Run` being a portion of text and `Span` being a group for other inline elements. All these are then collected by the control and rendered.
For a comprehensive demo of all the …
> Add support for RichTextBlock

- src/Avalonia.FuncUI/DSL/MaskedTextBox.fs
- src/Directory.Build.props
The control bindings introduced in #217 do not accept `MaskedTextBox` attributes currently because the attrs parameter is set to `TextBox`. Changing to `MaskedTextBox` accepts both, since the later already inherits from `TextBox` anyway.
Edited the contacts example to display this masked text box with a mask:
_(Won't be uploading this since some of the phone numbers don't follow that format and they don't work correctly, but it shows that the bindings work as the `mask` property is only available on `MaskedTextBox` and it was not being accepted before)_
Also bumping the preview version since I need this on one of my projects 😃
> Fix MaskedTextBox attributes

- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/DatePickerDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/TimePickerDemo.fs
- src/Avalonia.FuncUI/DSL/DatePicker.fs
- src/Avalonia.FuncUI/DSL/TimePicker.fs
I was looking at #232 and then also fell over https://github.com/AvaloniaUI/Avalonia/issues/9136, for which the header properties have been removed from the DatePicker and TimePicker controls.
So - this removes those.
That also required changes to the control catalog (I changed it to put a text block above the sample date/time controls to contain the header text)
> Remove the header properties from DatePicker and TimePicker

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
Elmish 4.0 introduced breaking changes, therefore Avalonia.FuncUI.Elmish doesn't work with that version (see #240). To avoid a non-working package resolution, I strictified the version requirement.
After that the generated .nupkg had the following dependencies:
```
Dependencies:
net6.0:
JaggerJo.Avalonia.FuncUI: '>= 0.6.04'
Elmish: '>= 3.1.0 && < 4.0.0'
FSharp.Core: '>= 7.0.0'
```
> Strictify Elmish dependency version

- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
Refs my comment in #222 about nuget.org currently showing the description as 'package description'...
Not sure what the text should be, so I just set it to the github about text to raise the question
> Add a package description field to the FuncUI project

- src/Examples/Component Examples/Examples.Presso/Styles/Styles.xaml
I was getting a build error about this with the latest Avalonia 11, but it appears that there is already a runtime error with the current code (were the xaml files copied from Example.Elmish.Presso without changing the namespaces?)
> Update the style references in the Examples.Presso project

- src/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/CalendarDatePickerDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/DatePickerDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/GridPatchDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/SplitViewDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/StylesDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/TextBoxDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/TickBarDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/TimePickerDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/ToggleSwitchDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/WrapPanelDemo.fs
- src/Avalonia.FuncUI.Diagnostics/Lib/Lib.ComponentAdorner.fs
- src/Avalonia.FuncUI.Diagnostics/Lib/Lib.Icons.fs
- src/Avalonia.FuncUI.Diagnostics/Views/Views.InspectorViews.fs
- src/Avalonia.FuncUI.Diagnostics/Views/Views.StateHookViews.fs
- src/Avalonia.FuncUI.Elmish/Library.fs
- src/Avalonia.FuncUI/Components/Context/Context.fs
- src/Avalonia.FuncUI/Components/State/State.Functions.fs
- src/Avalonia.FuncUI/Components/State/State.fs
- src/Avalonia.FuncUI/DSL/Base/Control.fs
- src/Avalonia.FuncUI/DSL/Button.fs
- src/Avalonia.FuncUI/DSL/DatePicker.fs
- src/Avalonia.FuncUI/DSL/Panels/Grid.fs
- src/Avalonia.FuncUI/DSL/Primitives/SelectingItemsControl.fs
- src/Avalonia.FuncUI/DSL/TextBox.fs
- src/Avalonia.FuncUI/DSL/TimePicker.fs
- src/Avalonia.FuncUI/DSL/TransitioningContentControl.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Delta.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Patcher.fs
- Removed unused namespace imports
- Prefixed unused parameters with an underscore
- Match all possible `Orientation` values
- Override the `GetHashCode` method of the `ViewDelta` type
The `Avalonia.FuncUI.Diagnostics.Reflector` type mentions a `Maecos.Shared.NonEmptyList` type (note a possible type in "Maecos") — https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Avalonia.FuncUI.Diagnostics/Lib/Lib.Reflector.fs#L46. Is it a correct string or a different type was meant there?
> Fix compilation warnings

- src/Avalonia.FuncUI/DSL/Base/Visual.fs
- src/Avalonia.FuncUI/DSL/LayoutTransformControl.fs
- src/Avalonia.FuncUI/Helpers.fs
- src/Examples/Component Examples/Examples.Presso/Program.fs
Provided a custom equality comparer for types implementing the `ITransform` interface. 
Types implementing the `ITransform` don't override equality methods, so using them in FuncUI means reassignments on every view generation (if transforms are created on the fly instead of reusing the same instance, producing an object not equal to the previous one even if it's created with the same constructor arguments as default `Equals` compares references). And such reassignment means an additional layout/redraw pass.
> Transform comparison

- README.md
Changes the README Documentation link 
From: https://avaloniacommunity.github.io/Avalonia.FuncUI.Docs/
To: https://funcui.avaloniaui.net/
> Updated "Documentation" link to Avalonia site

- src/Avalonia.FuncUI.Elmish/ElmishHook.fs
- src/Directory.Build.props
- src/Examples/Component Examples/Examples.ChordParser/ChordParserView.fs
Added an overload to `useElmish` hook that makes `initArg` does not need to be specified when `initArg` is `unit`. 
So this:
```F#
let model, dispatch = ctx.useElmish(init, update, ())
```
Can also be written as this:
```F#
let model, dispatch = ctx.useElmish(init, update)
```
> Elmish hook optional overloads

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
I noticed whilst looking at other things that the nuget packages didn't seem to specify what their license is - perhaps they should?
> Add a PackageLicenseExpression to the projects

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
There are a couple of build warnings about PackageIconUrl being deprecated - so, migrate the packages to PackageIcon
> Switch the nuget packages from PackageIconUrl to PackageIcon

- src/Avalonia.FuncUI/Components/Context/Context.fs
This means that if your default state is expensive to create, you don't need to create one (just to be discarded) every time the component is rendered.
> Create a useStateLazy method which takes a callback

- src/Avalonia.FuncUI/DSL/Buttons/ToggleButton.fs
refs this deprecation in Avalonia 11:
where ```IsCheckedChangedEvent``` is a new one.
This is perhaps a tad confusing in the bindings, where there is already an ```onIsCheckedChanged``` bound to ```IsCheckedProperty``` which is itself marked as obsolete, so not sure what the desired approach is there.
> Add a binding for ToggleButton.IsCheckedChangedEvent

- src/Avalonia.FuncUI/Builder.fs
(sort of) refs #281.
So... I've been using FuncUI to build an app that i've been publishing as a self contained, trimmed, exe (it's built with .NET 7, but you can run it without having to have an appropriate .NET version installed, and has fewer files to care about).
For various reasons (many things being broken basically), I've had it on partial trim mode so that it only trims libs that are explicitly marked as trimmable, whilst waiting for thins to get fixed or improve elsewhere. (e.g. the completion of some work in Avalonia to help it work better with trimming).
In Avalonia 11 Preview 6, parts of Avalonia are marked as trimmable, so they will be trimmed now when they weren't before. This should be quite nice as it will remove controls you aren't using and such, but alas it also causes …
> Add a DynamicallyAccessedMembers attribute to ViewBuilder.Create

- src/Avalonia.FuncUI/DSL/ItemsControl.fs
A couple of new properties on ItemsControl related to scrolling (for touch UI, but the size calculations they affect are performed for all UI).
> New properties in Avalonia supporting touch scrolling

- src/Avalonia.FuncUI.Diagnostics/Views/Views.StateHookViews.fs
- src/Avalonia.FuncUI.UnitTests/VirtualDom/VirtualDom.PatcherTests.fs
- src/Avalonia.FuncUI/DSL/AutoCompleteBox.fs
- src/Avalonia.FuncUI/DSL/Base/StyledElement.fs
- src/Avalonia.FuncUI/DSL/DataGrid.fs
- src/Avalonia.FuncUI/DSL/Flyout.fs
- src/Avalonia.FuncUI/DSL/ItemsControl.fs
- src/Avalonia.FuncUI/DSL/ScrollViewer.fs
- src/Avalonia.FuncUI/DSL/ViewBuilder.fs
- src/Directory.Build.props
A start on getting things working with preview 7.
main changes:
-The classes property is now read only
-Various controls have been changed to use ItemsSource instead of Items
-The Items property on ItemsControl has been made a regular instance property, which is read only
I tried changing ItemsControl.viewitems but haven't changed onItemsChanged and there is also a change needed to clipboard access in the diagnostics lib
> [wip] Start updating to Avalonia 11 preview 7

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/ControlCatalog.fs
- src/Avalonia.FuncUI/DSL/Base/Animatable.fs
- src/Avalonia.FuncUI/DSL/MenuBase.fs
- src/Avalonia.FuncUI/DSL/TabItem.fs
- src/Avalonia.FuncUI/DSL/TransitioningContentControl.fs
- src/Avalonia.FuncUI/VirtualDom/VirtualDom.fs
- src/Directory.Build.props
- src/Examples/Component Examples/Examples.Presso/Lib/Library.fs
- src/Examples/Elmish Examples/Examples.Elmish.MusicPlayer/Extensions.fs
- src/Examples/Elmish Examples/Examples.Elmish.Presso/Lib/Library.fs
Just another set of test changes to build with the latest Avalonia 11 nightly, as you can never break too many things
> Update to Avalonia 11 RC 1

- src/Avalonia.FuncUI/Components/Component.fs
- src/Avalonia.FuncUI/Components/StaticComponent.fs
- src/Avalonia.FuncUI/Environment.fs
- src/Avalonia.FuncUI/Hosts.fs
An attempt at fixing the deprection warnings in Avalonia 11 RC1, as described at https://github.com/AvaloniaUI/Avalonia/wiki/Avalonia-11-Porting-Guide#optional-but-recommended
> Replace uses of the deprecated IStyleable with StyleKeyOverride

- src/Avalonia.FuncUI/DSL/Panels/Canvas.fs
- src/Avalonia.FuncUI/DSL/Panels/DockPanel.fs
- src/Avalonia.FuncUI/DSL/Panels/Grid.fs
This may avoid scenarios like https://github.com/fsprojects/Avalonia.FuncUI/discussions/319 in the future.
> Documentation for attached properties

- src/Avalonia.FuncUI/DSL/View.fs
In response to https://github.com/fsprojects/Avalonia.FuncUI/discussions/350,
The ability to add attributes to a `View<_>` via |> `View.withAttrs [ ... ]`
> Add attributes to a view

- src/Examples/Component Examples/Examples.EnvApp/Program.fs
- src/Examples/Examples.DataGridPlayground/Program.fs
A couple of the example projects have the same window title as Examples.DrawingApp which can lead to confusion when looking at the examples. Maybe the titles can be even better but at least this fixes the ones that are incorrect.
> Fix example titles

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/GridSplitterDemo.fs
- src/Avalonia.FuncUI/DSL/GridSplitter.fs
This commit adds missing properties to GridSplitter, before no properties were implemented. It also adds GridSplitter Demo to the Controls Catalog.
GridSplitter.showsPreview seems to not be fully working in Avalonia at the moment (https://github.com/AvaloniaUI/Avalonia/issues/10700)
I am not sure how to test/demo GridSplitter.contentPreview since it's hard to find examples and documentation of usage but I think the types should be correct.
The GridSplitter demo allows you to play around with and test all the properties except .contentPreview
> Gridsplitter properties

- src/Avalonia.FuncUI/DSL/Panels/Grid.fs
This implements what was discussed in #365 
The hardest part is naming things, I ended up with duplicate DU:s (same DU cases) for the sizing called ColumnWidth and RowHeight as I had trouble coming up with a good name fitting both usages. GridSize was probably my best alternative but it reads like it applies to the Grid as a whole, I would be ok with changing to that though.
> Adding ColumnDefinition and RowDefinition to DSL

- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Patcher.fs
I've been having a go with with the [F# analyzers](http://ionide.io/FSharp.Analyzers.SDK/) tools, and got this suggestion that using List.iteri rather than Seq.iteri when the collection is known to be a list should be more efficient
```
Avalonia.FuncUI\VirtualDom\VirtualDom.Patcher.fs(92,25): Warning GRA-VIRTUALCALL-001 - Consider replacing the call of Seq.iteri with a function from the List module to avoid the costs of virtual calls.
```
> Replace a use of Seq.iteri over a list with List.iteri

- .github/workflows/pull-requests.yml
refs #380 and the build failure in #381
> Use 'dotnet workload restore' to restore workloads in the PR CI builds

- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Avalonia.FuncUI/DSL/PathIcon.fs
https://github.com/fsprojects/Avalonia.FuncUI/issues/381
> Added PathIcon Control

- src/Avalonia.FuncUI.UnitTests/Avalonia.FuncUI.UnitTests.fsproj
This is pretty trivial, but - 
The NuGet vulnerability reporting feature in the latest Visual Studio reports a warning about a transient dependency in the unit tests project:
Updating the unit testing libs to the latest version trims out a huge amount of transitive dependencies on rather old versions of things, which sorts that but also makes the dependencies much cleaner:
> Update unit testing libraries

- .github/workflows/pull-requests.yml
I noticed this in the build results when looking at other things:
so lets try updating the actions
> Update Github actions in the PR build pipeline

- src/Avalonia.FuncUI/DSL/DataGrid.fs
- src/Examples/Examples.DataGridPlayground/Program.fs
Adds the following functions to the `DataGrid` control:
* `selectedIndex`
* `onSelectedIndexChanged`
* `selectedItem`
* `selection`
* `onSelectedItemChanged`
* `onSelectionChanged`
> Port SelectingItemsBehavior to DataGrid

- src/Avalonia.FuncUI/DSL/DataGrid.fs
Context from the Avalonia docs: https://reference.avaloniaui.net/api/Avalonia.Controls/DataGridBoundColumn/21520FC9
One issue with DataGrid in FuncUI is that copying is only limited to the whole row. Setting this property should allow users to copy the cells they are selecting.
> Add static property ClipboardContentBinding to DataGridBoundColumn

- src/Avalonia.FuncUI/DSL/Buttons/Button.fs
Opening an old project I had, I noticed that it was breaking because of the `isPressed` not being public. Went onto check on the repo and upon adding `Button.isPressed true` to the counter example, it breaks as well:
```
Unhandled exception. System.ArgumentException: The property IsPressed is readonly.
at Avalonia.DirectProperty`2.InvokeSetter(AvaloniaObject instance, BindingValue`1 value) in /_/src/Avalonia.Base/DirectProperty.cs:line 120
at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 749
at Avalonia.AvaloniaObject.SetValue[T](DirectPropertyBase`1 property, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 355
at Avalonia.DirectPropertyBase`1.RouteSetValue(AvaloniaObject o, Object value, …
```
> Remove isPressed property setter

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
Rather simple, but - thought i'd sort the items before adding anything new (the catalog in Avalonia itself is sorted, so may as well be consistent...)
> Sort the control items in the control catalog into alphabetical order

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
I thought this had been done a while back, but apparently not -
> Add a NuGet description property to the Elmish project.

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/AttachedEventDemo.fs
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Avalonia.FuncUI/DSL/AttrBuilder.fs
- src/Avalonia.FuncUI/DSL/Base/Interactive.fs
There are times when you want to know the current state of the sender in a RoutedEvent.
This PR adds generic bindings that can be used in such cases.
> Add generic RoutedEvent bindings as Attached Event.

- docs/common-questions.md
- docs/components/component-basics.md
- docs/components/component-lifetime.md
- docs/components/hooks.md
- docs/view-basics/attributes.md
- docs/view-basics/creating-views.md
- docs/view-basics/how-to-create-bindings.md
- docs/view-basics/lifetime.md
I was reading the docs and noticed some spelling errors, so I went and fixed those that I saw.
> Fix spelling/grammar errors in the docs

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/WindowMenuDemo.fs
- src/Avalonia.FuncUI/DSL/MenuItem.fs
Added to Avalonia in https://github.com/AvaloniaUI/Avalonia/pull/11441
refs #431 
Also adds radio buttons to the control catalog menu page as a really simple example:
> Add ToggleType and related properties to MenuItem

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.Desktop/Avalonia.FuncUI.ControlCatalog.Desktop.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/DataTemplateDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/DragDropDemo.fs
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/GridDemo.fs
The main issue besides the dynamically loaded xaml being trimmed out (avoided for now by rooting the control catalog assembly) is that it seems to not like using ```sprintf``` in views, e.g.
```
Unhandled Exception: System.NotSupportedException: 'Microsoft.FSharp.Core.PrintfImpl+Specializations`3[Microsoft.FSharp.Core.Unit,System.String,System.String].CaptureFinal1[System.Int32](Microsoft.FSharp.Core.PrintfImpl+Step[])' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x2f
at …
```
> Try to get the control catalog working in NativeAOT builds

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/DragDropDemo.fs
refs 
Should these have been changed in https://github.com/fsprojects/Avalonia.FuncUI/commit/46d44d821093e56da16e114386c4cea02faaf504 ?
> Try to fix compile errors in DragDropDemo

- global.json
refs https://github.com/fsprojects/Avalonia.FuncUI/issues/449
I was going to update FSharp.Core to 8.0.300, but then I see there are discussions in https://github.com/dotnet/fsharp/issues/18298 about reverting the compiler changes, so maybe we should see where that goes before making public changes
> Add a global.json to pin the builds to the .NET 8 SDK for now

- .github/workflows/pull-requests.yml
The CI build now seems to be having issues building the iOS examples:
```
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 18.0 SDK (shipped with Xcode 16.0). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/Avalonia.FuncUI/Avalonia.FuncUI/src/Examples/Examples.Mobile.iOS/Examples.Mobile.iOS.fsproj]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 18.0 SDK (shipped with Xcode 16.0). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build …
```
> Use XCode 16 in the CI builds

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Views/Tabs/HyperlinkButtonDemo.fs
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Avalonia.FuncUI/DSL/Buttons/HyperlinkButton.fs
Rather simple, but goes along side the bindings for the other button classes.
Could maybe do with a page in the docs as well though.
> Add bindings for HyperlinkButton

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Directory.Build.props
refs https://github.com/fsprojects/Avalonia.FuncUI/pull/459#discussion_r2052340926
Should PackageVersion be common as well? (I guess the core lib and the elmish lib should be in step, not sure about the diagnostics lib if that gets published again)
> Move common NuGet package properties into Directory.Build.props

- docs/README.md
refs https://github.com/fsprojects/Avalonia.FuncUI/issues/463#issuecomment-2867915581
I think it should point out that the current FuncUI requires at least Avalona 11.1.0, and when looking I also noticed that the  hyperlinks to nuget.org were pointing at old preview packages instead of the release versions
> Update nuget package versions in the getting started docs

- src/Avalonia.FuncUI/DSL/Border.fs
Was just having a look over the list of new properties that were added in Avalonia 11.1 that don't have bindings yet, and this new Border.BackgroundSizingProperty``` appears to be one
> Add a binding for Border.BackgroundSizing
