fsprojects/Avalonia.FuncUI

- src/Avalonia.FuncUI/DSL.attrs.fs
- src/Examples/CounterElmishExample/Counter.fs
Add most missing attached properties.
> Add missing attached properties

- src/Avalonia.FuncUI.sln
- src/Templates/TemplateBundle/TemplateBundle.fsproj
- src/Templates/TemplateBundle/content/BasicTemplate/.template.config/template.json
- src/Templates/TemplateBundle/content/BasicTemplate/AppView.fs
- src/Templates/TemplateBundle/content/BasicTemplate/BasicTemplate.fsproj
- src/Templates/TemplateBundle/content/BasicTemplate/Lib.fs
- src/Templates/TemplateBundle/content/BasicTemplate/Main.fs
- create "bundle" project
- edit structure of underlaying tem,plates (currently only one)
- a few small refinements
> finish templates

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/MenuDemo.fs
- src/Avalonia.FuncUI.DSL/Avalonia.FuncUI.DSL.fsproj
- src/Avalonia.FuncUI.DSL/Base/InputElement.fs
- src/Avalonia.FuncUI.DSL/ContextMenu.fs
- src/Avalonia.FuncUI.DSL/DataValidationErrors.fs
- src/Avalonia.FuncUI.DSL/Decorator.fs
- src/Avalonia.FuncUI.DSL/DrawingPresenter.fs
- src/Avalonia.FuncUI.DSL/Expander.fs
- src/Avalonia.FuncUI.DSL/GridSplitter.fs
- src/Avalonia.FuncUI.DSL/LayoutTransformControl.fs
- src/Avalonia.FuncUI.DSL/Menu.fs
- src/Avalonia.FuncUI.DSL/MenuBase.fs
- src/Avalonia.FuncUI.DSL/MenuItem.fs
- src/Avalonia.FuncUI.DSL/Primitives/AccessText.fs
- src/Avalonia.FuncUI.DSL/TextBox.fs
- src/Examples/Examples.GameOfLife/Board.fs
- AccessText
- Decorator
- MenuBase
- Menu
- ContextMenu
- MenuItem
- LayoutTransformControl
- Expander
- DrawingPresenter
- GridSplitter
- DataValidationErrors
> Add more DSL Bindings

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/TextBoxDemo.fs
- src/Avalonia.FuncUI.DSL/TextBox.fs
Hello there!
<details>
<summary>
First of all, this is such an awesome project :sunglasses:
</summary
<p>
I've been really enjoying doing some toy apps with this, and next time I'm doing something for desktop I'm sure I'll pick this to work with
</p>
</details>
I noticed the watermark property was missing from the textbox and I decided to give it a shot, I added also a page in the control catalog project with a small watermark sample, but I'm not sure if that's a good place to put it or should it go as a different example Please let me know where should it go and I can make the changes also if I should add more to it rather than just a textbox with watermarks
> Add Textbox Watermark

- src/Avalonia.FuncUI/VirtualDom/VirtualDom.Differ.fs
> fix subscription does not provide reset operation

- src/Examples/Examples.MusicPlayer/Examples.MusicPlayer.fsproj
- src/Examples/Examples.MusicPlayer/Icons.fs
- src/Examples/Examples.MusicPlayer/Player.fs
- src/Examples/Examples.MusicPlayer/Playlist.fs
- src/Examples/Examples.MusicPlayer/Program.fs
- src/Examples/Examples.MusicPlayer/Shell.fs
Hey @AngelMunoz,
hope you don't mind that I reformatted the views. No idea why but I really prefer this formatting.
> Mediaplayer macOS VLC  native support and view format

- src/Avalonia.FuncUI/Components/DataTemplateView.fs
- src/Examples/Examples.Presso/Lib/Library.fs
Now it allows for the viewFunc to return just an IView, which can be useful when e.g. viewFunc returns two different control types depending on the condition.
> Relaxed the type of view func

- src/Avalonia.FuncUI/Components/DataTemplateView.fs
@JaggerJo Fixes https://github.com/AvaloniaCommunity/Avalonia.FuncUI/issues/99
> Fixed DataTemplateView.Match method

- src/Avalonia.FuncUI.DSL/ToggleButton.fs
@JaggerJo @AngelMunoz Could you please review this?
> Added a subscription to ToggleButton.Indeterminate event

- src/Avalonia.FuncUI.sln
Since docs was transferred into separate repo there is no such project as docs
> Remove docs project from solution

- src/Avalonia.FuncUI/Components/DataTemplateView.fs
This PR allows to define non-recursive DataTemplates.
This complicates the code and adds another generic type to it. I hope that's okay.
> Allow non-recursive DataTemplates

- src/Avalonia.FuncUI.DSL/AutoCompleteBox.fs
- src/Avalonia.FuncUI.DSL/Base/Visual.fs
- src/Avalonia.FuncUI.DSL/Decorator.fs
- src/Avalonia.FuncUI.DSL/Image.fs
- src/Avalonia.FuncUI.DSL/LayoutTransformControl.fs
- src/Avalonia.FuncUI.DSL/Primitives/Popup.fs
- src/Avalonia.FuncUI.DSL/TabControl.fs
- src/Avalonia.FuncUI/Builder.fs
> Fix some property bindings which fail at runtime, including Image.source

- .github/workflows/publish.yml
- README.md
- src/Avalonia.FuncUI.DSL/Avalonia.FuncUI.DSL.fsproj
- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI.sln
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Examples/Component Examples/Examples.ChordParser/Examples.ChordParser.fsproj
- src/Examples/Component Examples/Examples.CounterApp/Examples.CounterApp.fsproj
- src/Examples/Component Examples/Examples.CounterApp/Main.fs
- src/Examples/Component Examples/Examples.CounterApp/Program.fs
**On this episode of Avalonia.FuncUI**
- Fix the problem that is currently failing the CI in master
- Upgrade all packages to 0.5.0 (basically remove the `-beta`)
- Port counter app example to components
- Add a stripped down counter example to README and add/modify some of the content
> Avalonia.FuncUI 0.5 release

- src/Avalonia.FuncUI.Templates/README.md
Quickly applying the suggestion that Angel left on the other PR, since I can't push stuff directly into master 😃
> Remove app name from run command in template's README

- src/Avalonia.FuncUI.Diagnostics/Avalonia.FuncUI.Diagnostics.fsproj
- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Directory.Build.props
This PR publishes the diagnostics package, since I think it'd be useful outside of this repo as well (at least I missed it in my projects 😄). Unless you'd like to keep it private @JaggerJo.
Also, I've moved all the versioning of the packages to the centralized place introduced in #213 so that we can easily keep all packages in sync.
> Publish diagnostics + version housekeeping

- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Views/MainView.fs
- src/Avalonia.FuncUI.ControlCatalog/Views/Tabs/FlyoutDemo.fs
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
- src/Avalonia.FuncUI/DSL/Button.fs
- src/Avalonia.FuncUI/DSL/Flyout.fs
Add Flyout component support with demo according to issue #227
> Flyout component support

- src/Avalonia.FuncUI.Templates/README.md
this adds a correction to the spelling issue introduced with the new templates
> update funcui to funcUI

- src/Directory.Build.props
> bump to v0.6.0-preview6

- src/Avalonia.FuncUI.Elmish/ElmishHook.fs
- src/Directory.Build.props
@sleepyfran,
This contains a small bugfix for the new `useElmish` hook found in [discussion 255](https://github.com/fsprojects/Avalonia.FuncUI/discussions/256).
I bumped version to "preview6.1" since it's just a bugfix to preview6.
> useElmish bugfix - v0.6.0-preview6.1

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
- src/Avalonia.FuncUI/Avalonia.FuncUI.fsproj
Using the approach of putting the .pdb files into the nuget packages
> Add SourceLink to the projects

- src/Directory.Build.props
Release of latest changes including `Control.init` feature (requested in #153)
> 0.6.0-preview8

- src/Avalonia.FuncUI/DSL/Base/StyledElement.fs
https://github.com/fsprojects/Avalonia.FuncUI/issues/294
> Add theme binding

- src/Avalonia.FuncUI.sln
Previously, the solution contained the `Examples.Mobile` folder but there were no projects there.
> Restored the iOS sample in the solution

- src/Examples/Component Examples/Examples.GeneticAlgorithm/Lib/Simulator.fs
Edit formatting of records in [Simulator.fs](https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Examples/Component%20Examples/Examples.GeneticAlgorithm/Lib/Simulator.fs) to remove some build warnings.
> Fix indentation warnings in Genetic algo

- src/Avalonia.FuncUI/DSL/ItemsControl.fs
- src/Avalonia.FuncUI/DSL/Panels/StackPanel.fs
- src/Directory.Build.props
Just starting to update ready for the next version whilst I've got a spare minute.
Some functions were removed from ItemsControl is https://github.com/AvaloniaUI/Avalonia/pull/11752, and I noticed that the same properties also exist on StackPanel and didn't have bindings, so I added them at the same time
> Update to Avalonia 11.0.0-rc2.2

- src/Avalonia.FuncUI.sln
- src/Examples/Elmish Examples/Examples.Elmish.Tetris/Examples.Elmish.Tetris.fsproj
- src/Examples/Elmish Examples/Examples.Elmish.Tetris/Program.fs
- src/Examples/Elmish Examples/Examples.Elmish.Tetris/README.md
- src/Examples/Elmish Examples/Examples.Elmish.Tetris/Tetris.Core.fs
- src/Examples/Elmish Examples/Examples.Elmish.Tetris/Tetris.fs
- src/Examples/Elmish Examples/Examples.Elmish.Tetris/View.fs
ref: https://github.com/RyushiAok/Tetris/issues/2
> Add Tetris Example

- src/Avalonia.FuncUI/Components/Component.fs
Fixes https://github.com/fsprojects/Avalonia.FuncUI/discussions/349
> Perform the Update from OnInitialized synchronously

- .github/workflows/pull-requests.yml
refs https://github.com/fsprojects/Avalonia.FuncUI/pull/383#issuecomment-1881739616 and the way that the CI run for #385 seems to have broken because of it - so lets see what happens without it there
> Try running PR build with xcode 15.1 instead of 14.3

- src/Avalonia.FuncUI.Benchmarks/Avalonia.FuncUI.Benchmarks.fsproj
- src/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog/Avalonia.FuncUI.ControlCatalog.fsproj
- src/Avalonia.FuncUI.UnitTests/Avalonia.FuncUI.UnitTests.fsproj
- src/Examples/Component Examples/Examples.ContactBook/Examples.ContactBook.fsproj
Lets get these updated to the current versions to go along with the .NET 8 / Avalonia 11.1 updates
> Update all the unit testing and related libs

- src/Avalonia.FuncUI.Elmish/Avalonia.FuncUI.Elmish.fsproj
refs https://github.com/fsprojects/Avalonia.FuncUI/issues/434#issuecomment-2785974605
> Update Elmish to 4.3.0
